production:
  adapter: postgresql
  encoding: unicode
  database: filter_app
  username: ic
  password: covid_postgres_1
  host: ls-a89078db59e133bc13581e4d12fcfe8925ab4a3d.ctmafl6zftgj.us-west-2.rds.amazonaws.com